=== gabrielasoma/Ejercicios-HTML/html/3º eval/examen1/xml/empleado/src/main/java/empleado.dtd
<?xml version="1.0" encoding="UTF-8"?>



<!ELEMENT empleados (empleado+,cargos)+>
<!ELEMENT empleado (#PCDATA)>
    <!ATTLIST empleado codEmpl ID #REQUIRED>
    
<!ELEMENT cargos (cargo+)>
<!ELEMENT cargo (#PCDATA)>
   <!ATTLIST cargo ejecutivo IDREFS #REQUIRED>

=== gabrielasoma/Ejercicios-HTML/html/examen1/xml/empleado/src/main/java/empleado.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE empleados SYSTEM "empleado.dtd">

<empleados>
    <empleado codEmpl="E1">Carlos</empleado>
    <empleado codEmpl="E2">Mar√≠a</empleado>
    <empleado codEmpl="E3">Luis</empleado>
    <empleado codEmpl="E4">Ana</empleado>
    <empleado codEmpl="E5">Pedro</empleado>


<cargos>
    <cargo ejecutivo="E1">Director</cargo>
    <cargo ejecutivo="E3">Financiero</cargo>
    <cargo ejecutivo="E4">Recursos</cargo>
    <cargo ejecutivo="E2 E5">Comerciales</cargo>
</cargos>  
</empleados>
