=== gabrielasoma/Ejercicios-HTML/xml dtd/todoLM/src/componente1.dtd
<?xml version="1.0" encoding="UTF-8"?>

    <!ELEMENT componentes (resistencia | condensador)+>
    
    <!ELEMENT resistencia (nombre,tipo,precio,medida)>
    <!ELEMENT condensador (nombre,tipo,precio,medida)>

    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT medida (#PCDATA)>

=== gabrielasoma/Ejercicios-HTML/xml dtd/todoLM/src/componente1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE componentes SYSTEM "componente1.dtd">

<componentes>
    <resistencia>
        <nombre>Elias Machine</nombre>
        <tipo>Peruano</tipo>
        <precio>12,00</precio>
        <medida>3cm</medida>
    </resistencia>

    <condensador>
        <nombre>Alpine</nombre>
        <tipo>Carromato</tipo>
        <precio>10000â‚¬</precio>
        <medida>3m</medida>
    </condensador>

</componentes>
