<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE familia [
    <!ELEMENT familia (((padre,madre) | (padre,madre?) | (padre?,madre) | (padre?,madre?) | (padre,padre) | (madre,madre)),hijos+)>
    
    <!ENTITY  % info_familia "(nombre,apellido,apellido,dni?,edad?)" >
    
    <!ELEMENT hijos (hijo,hija)+>
    
    <!ELEMENT padre %info_familia;>
    <!ELEMENT madre % info_familia;>
    <!ELEMENT hijo %info_familia;>
    <!ELEMENT hija %info_familia;>
    
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT dni (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>
    
    <!ATTLIST familia codigo ID #REQUIRED>
    <!ATTLIST hijo pos NMTOKEN #REQUIRED>
    <!ATTLIST hija pos NMTOKEN #REQUIRED>
]>


<familia codigo="P01-7">
    <padre>
        <nombre>Antonio</nombre>
        <apellido>Perez</apellido>
        <apellido>Rodrigez</apellido>
        <edad>12.345.678-A</edad>
    </padre>

    <madre>
        <nombre>Elena</nombre>
        <apellido>Roldan</apellido>
        <apellido>Benitez</apellido>
        <edad>90.123.456-B</edad>
    </madre>


    <hijos>
        <hijo pos="2">
            <nombre>Alejandro</nombre>
            <apellido>Perez</apellido>
            <apellido>Roldan</apellido>
            <edad>12</edad> 
        </hijo>
       
        <hijo pos="3">
            <nombre>Manuel</nombre>
            <apellido>Perez</apellido>
            <apellido>Roldan</apellido>
            <edad>6</edad>
        </hijo>
        
        <hija pos="1">
            <nombre>Elena</nombre>
            <apellido>Perez</apellido>
            <apellido>Roldan</apellido>
            <dni>78.345.678-C</dni>
        </hija>
        
    </hijos>
  
</familia>
