=== gabrielasoma/Ejercicios-HTML/html/3º eval/examen1/DtdTiendaDeportiva.dtd
<?xml version="1.0" encoding="UTF-8"?>

    <!ELEMENT tienda (raqueta+)>

    <!ELEMENT raqueta (marca,modelo,anio,precio,almacen)>
         <!ATTLIST raqueta id CDATA #REQUIRED>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT anio (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT almacen (#PCDATA)>

=== gabrielasoma/Ejercicios-HTML/html/3º eval/examen1/TiendaDeportiva.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE tienda SYSTEM "DtdTiendaDeportiva.dtd">-->
<?xml-stylesheet href="raqueta.css"?>
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="EsquemaTiendaDeportiva.xsd">
    <raqueta id="1">
        <marca>Wilson</marca>
        <modelo>Ultra Team</modelo>
        <anio>2019</anio>
        <precio>100.50</precio>
        <almacen>B-2020</almacen>
    </raqueta>
    <raqueta id="2">
        <marca>Prince</marca>
        <modelo>Hornet 100</modelo>
        <anio>2019</anio>
        <precio>80.89</precio>
        <almacen>A-2019</almacen>
    </raqueta>
</tienda>
