<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE componentes[
<!ELEMENT componentes (resistencias | condensadores)+>

<!ELEMENT resistencia (nombre+, tipo+, precio, medida)>
<!ELEMENT condensadores (nombre+, tipo+, precio, medida)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT medida (#PCDATA)>

]>


<componentes>
    
    <resistencias>
        <nombre>Elias Machine</nombre>
        <tipo>Peruano</tipo>
        <precio>12,00€</precio>
        <medida>3cm</medida>
    </resistencias>
    
    
    <condenasdores>
        <nombre>Alpine</nombre>
        <tipo>Carromato</tipo>
        <precio>10000€</precio>
        <medida>3m</medida>
    </condenasdores>
    
</componentes>
