=== gabrielasoma/Ejercicios-HTML/xml dtd/comunidadVecinos1/src/vecinos.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="comunidad">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="vecino" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            
        </xs:complexType>
       
        
    </xs:element>
    <xs:element name="vecino">
        <xs:complexType>
            <xs:sequence>
                  <xs:element ref="nombre" minOccurs="1" maxOccurs="unbounded"/>
                 <xs:element ref="apellido" minOccurs="1" maxOccurs="unbounded"/>
                 <xs:element ref="portal" minOccurs="1" maxOccurs="unbounded"/>
                 <xs:element ref="PisoLetra" minOccurs="1" maxOccurs="unbounded"/>
                 <xs:element ref="CCC" minOccurs="0" maxOccurs="unbounded"/>
                 <xs:element ref="cargo" minOccurs="1" maxOccurs="unbounded"/>
                 
            </xs:sequence>
            <xs:attribute name="ref" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="apellido" type="xs:string"/>
    <xs:element name="portal" type="xs:string"/>
    <xs:element name="PisoLetra" type="xs:string"/>
    <xs:element name="CCC" type="xs:string"/>
    <xs:element name="cargo" type="xs:string"/>

</xs:schema>

=== gabrielasoma/Ejercicios-HTML/xml dtd/comunidadVecinos1/src/comunidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE comunidad [
<!ELEMENT comunidad (vecino)+>
<!ELEMENT vecino (nombre,apellido+,portal,PisoLetra,CCC?,cargo)>
    <!ATTLIST vecino ref CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT portal (#PCDATA)>
<!ELEMENT PisoLetra (#PCDATA)>
<!ELEMENT CCC (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>


]>
-->
<comunidad xsi:noNamespaceSchemaLocation="vecinos.xsd" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <vecino ref="1">
        <nombre>David</nombre>
        <apellido>Sánchez</apellido>
        <apellido>Garcia</apellido>
        <portal>132</portal>
        <PisoLetra>5C</PisoLetra>
        <CCC>2020 1480 25 6598565214</CCC>
        <cargo>Presidente</cargo>
     
    </vecino>
    <vecino ref="10">
        <nombre>Elena</nombre>
        <apellido>Pérez</apellido>
        <portal>48</portal>
        <PisoLetra>2B</PisoLetra>
        <cargo>Vicepresidenta</cargo>
     
    </vecino>




</comunidad>

=== gabrielasoma/Ejercicios-HTML/xml dtd/IntentoComunidad/build/classes/comunidad.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE comunidad [
<!ELEMENT comunidad (vecino)+>

<!ELEMENT vecino (nombre,apellido+,portal,PisoLetra,CCC?,cargo)>
    <!ATTLIST vecino ref CDATA #REQUIRED>
    
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT portal (#PCDATA)>
<!ELEMENT PisoLetra (#PCDATA)>
<!ELEMENT CCC (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>
]>

<comunidad xsi:noNamespaceSchemaLocation="vecinos.xsd" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema">
    
    <vecino ref="1">
        <nombre>David</nombre>
        <apellido>Sánches</apellido>
        <apellido>García</apellido>
        <portal>123</portal>
        <PisoLetra>5C</PisoLetra>
        <CCC>2020 1480 25 6598565214</CCC>
        <cargo>Presidente</cargo>
    </vecino>


    <vecino ref="10">
        <nombre>Elena</nombre>
        <apellido>Pérez</apellido>
        <portal>48</portal>
        <PisoLetra>2B</PisoLetra>
        <cargo>Viceprecidenta</cargo>
    </vecino>

</comunidad>
